# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s3X-vRjsR7BGtdk6COayYJSwMEkFMNXg
"""

!pip install streamlit

pip install pymupdf

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# st.set_page_config(
#     page_title = "AI JOB APPLICATION ANALYZER",
#     page_icon = "🤖"
# )
# 
# st.title("🤖 AI JOB APPLICATION ALANYZER")
# 
# st.write("My streamlit application is working!")

!cat app.py

!streamlit run app.py &>/content/streamlit.log &

!cat /content/streamlit.log

!pip install pyngrok

#creating a public link
from pyngrok import ngrok

ngrok.set_auth_token("3IMGVzWuJmZy4CSZEpICYMWG00L_6gAuzbs1K1eneF9ejGvR1")

public_url = ngrok.connect(8502)

print("Streamlit App URL: ")
print(public_url)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import fitz
# import os
# 
# from google import genai
# 
# from sklearn.feature_extraction.text import TfidfVectorizer
# from sklearn.metrics.pairwise import cosine_similarity
# 
# 
# 
# 
# # ============================================================
# # PAGE CONFIGURATION
# # ============================================================
# 
# st.set_page_config(
#     page_title="AI Job Application Analyzer",
#     page_icon="🤖",
#     layout="wide"
# )
# 
# #Custom UI Styling
# 
# st.markdown("""
# <style>
# 
# .stApp {
#     background: linear-gradient(
#         135deg,
#         #0f172a 0%,
#         #111827 50%,
#         #172554 100%
#     );
#     color: #f8fafc;
# }
# 
# .main .block-container {
#     max-width: 1200px;
#     padding-top: 2rem;
#     padding-bottom: 3rem;
# }
# 
# .main-title {
#     text-align: center;
#     font-size: 42px;
#     font-weight: 700;
#     margin-bottom: 5px;
# }
# 
# .subtitle {
#     text-align: center;
#     font-size: 18px;
#     color: #cbd5e1;
#     margin-bottom: 35px;
# }
# 
# .score-card {
#     background: rgba(30, 41, 59, 0.85);
#     border: 1px solid rgba(148, 163, 184, 0.2);
#     border-radius: 18px;
#     padding: 25px;
#     text-align: center;
#     box-shadow: 0 10px 30px rgba(0, 0, 0, 0.25);
# }
# 
# .score-title {
#     font-size: 38px;
#     font-weight: 700;
#     margin-top: 8px;
# }
# 
# h2, h3 {
#     color: #f8fafc !important;
# }
# 
# .stButton > button {
#     width: 100%;
#     border-radius: 12px;
#     padding: 12px;
#     font-size: 17px;
#     font-weight: 600;
#     border: none;
#     background: #2563eb;
#     color: white;
# }
# 
# .stButton > button:hover {
#     background: #1d4ed8;
# }
# 
# textarea {
#     background-color: #1e293b !important;
#     color: #f8fafc !important;
#     border-radius: 12px !important;
# }
# 
# [data-testid="stFileUploader"] {
#     background: #1e293b;
#     border-radius: 15px;
#     padding: 10px;
# }
# 
# .gemini-box {
#     background: rgba(30, 41, 59, 0.9);
#     border-left: 4px solid #3b82f6;
#     border-radius: 12px;
#     padding: 25px;
#     margin-top: 20px;
# }
# 
# </style>
# """, unsafe_allow_html=True)
# # ============================================================
# # TITLE
# # ============================================================
# 
# st.markdown(
#     '<div class="main-title">🤖 AI Job Application Analyzer</div>',
#     unsafe_allow_html=True
# )
# 
# st.markdown(
#     '<div class="subtitle">AI-powered Resume & Job Description Matching</div>',
#     unsafe_allow_html=True
# )
# 
# st.write(
#     "Analyze how closely your resume matches a job description "
#     "using NLP and Generative AI."
# )
# 
# # ============================================================
# # GEMINI AI ANALYSIS
# # ============================================================
# 
# def analyze_with_gemini(resume_text, job_description):
# 
#     api_key = os.environ.get("GEMINI_API_KEY")
# 
#     if not api_key:
#         return "Gemini API key not configured."
# 
#     client = genai.Client(
#         api_key=api_key
#     )
# 
#     prompt = f"""
# You are an AI job application analyzer.
# 
# Analyze the candidate's resume against the job description.
# 
# RESUME:
# {resume_text}
# 
# JOB DESCRIPTION:
# {job_description}
# 
# Provide the analysis in the following format:
# 
# ### Overall Assessment
# 
# Give a short assessment of how well the candidate fits the role.
# 
# ### Relevant Strengths
# 
# List 3-5 strengths from the resume that match the job description.
# 
# ### Missing or Weak Areas
# 
# List the most important skills or requirements that are missing
# or not strongly demonstrated.
# 
# ### Resume Improvement Suggestions
# 
# Give 3-5 specific suggestions to improve the resume for this role.
# 
# ### Technical Interview Questions
# 
# Generate 5 technical interview questions relevant to this job
# and the candidate's background.
# """
# 
#     response = client.models.generate_content(
#         model="gemini-3.6-flash",
#         contents=prompt
#     )
# 
#     return response.text
# 
# 
# # ============================================================
# # SKILL DICTIONARY
# # ============================================================
# 
# skill_aliases = {
#     "Python": ["python"],
#     "SQL": ["sql"],
#     "Machine Learning": ["machine learning"],
#     "Deep Learning": ["deep learning"],
#     "Scikit-learn": ["scikit-learn", "sklearn"],
#     "TensorFlow": ["tensorflow"],
#     "PyTorch": ["pytorch"],
#     "LLM": ["llm", "llms", "large language model"],
#     "REST API": ["rest api", "restful api"],
#     "Git": ["git"],
#     "GitHub": ["github"],
#     "Cloud": ["cloud", "cloud-based", "cloud-native"],
#     "Data Engineering": ["data engineering"],
#     "Data Science": ["data science"],
#     "Data Analysis": ["data analysis"],
#     "Data Visualization": ["data visualization"],
#     "ETL": ["etl"],
#     "Pandas": ["pandas"],
#     "NumPy": ["numpy"],
#     "XGBoost": ["xgboost"],
#     "OIC": ["oic", "oracle integration cloud"],
#     "OCI": ["oci", "oracle cloud infrastructure"],
#     "Oracle APEX": ["oracle apex"],
#     "Oracle VBCS": ["oracle vbcs", "vbcs"],
#     "SFTP": ["sftp"],
#     "Random Forest": ["random forest"],
#     "K-Means": ["k-means", "k means", "kmeans"],
#     "LSTM": ["lstm"],
#     "Matplotlib": ["matplotlib"],
#     "Seaborn": ["seaborn"],
#     "Model Monitoring": ["model monitoring"]
# }
# 
# 
# # ============================================================
# # PDF TEXT EXTRACTION
# # ============================================================
# 
# def extract_resume_text(uploaded_file):
# 
#     pdf_bytes = uploaded_file.read()
# 
#     document = fitz.open(
#         stream=pdf_bytes,
#         filetype="pdf"
#     )
# 
#     text = ""
# 
#     for page in document:
#         text += page.get_text()
# 
#     document.close()
# 
#     return text
# 
# 
# # ============================================================
# # TEXT SIMILARITY
# # ============================================================
# 
# def calculate_text_similarity(resume_text, job_description):
# 
#     vectorizer = TfidfVectorizer(
#         stop_words="english"
#     )
# 
#     matrix = vectorizer.fit_transform(
#         [resume_text, job_description]
#     )
# 
#     similarity = cosine_similarity(
#         matrix[0:1],
#         matrix[1:2]
#     )[0][0]
# 
#     return similarity * 100
# 
# 
# # ============================================================
# # SKILL DETECTION
# # ============================================================
# 
# def detect_skills(text):
# 
#     text_lower = text.lower()
# 
#     detected_skills = []
# 
#     for skill, aliases in skill_aliases.items():
# 
#         for alias in aliases:
# 
#             if alias.lower() in text_lower:
#                 detected_skills.append(skill)
#                 break
# 
#     return sorted(set(detected_skills))
# 
# 
# # ============================================================
# # SKILL MATCHING
# # ============================================================
# 
# def calculate_skill_match(resume_text, job_description):
# 
#     resume_skills = detect_skills(resume_text)
# 
#     job_skills = detect_skills(job_description)
# 
#     matched_skills = sorted(
#         set(resume_skills) & set(job_skills)
#     )
# 
#     missing_skills = sorted(
#         set(job_skills) - set(resume_skills)
#     )
# 
#     additional_skills = sorted(
#         set(resume_skills) - set(job_skills)
#     )
# 
#     if len(job_skills) > 0:
# 
#         skill_score = (
#             len(matched_skills) / len(job_skills)
#         ) * 100
# 
#     else:
# 
#         skill_score = 0
# 
#     return (
#         skill_score,
#         matched_skills,
#         missing_skills,
#         additional_skills
#     )
# 
# 
# # ============================================================
# # USER INPUT
# # ============================================================
# 
# st.markdown(
#     '<p style="color:white; font-size:20px; font-weight:600;">📄 Upload Resume (PDF)</p>',
#     unsafe_allow_html=True
# )
# 
# uploaded_file = st.file_uploader(
#     "Choose a PDF file",
#     type=["pdf"]
# )
# 
# st.markdown(
#     '<p style="color:white; font-size:20px; font-weight:600;">📋 Paste Job Description</p>',
#     unsafe_allow_html=True
# )
# 
# job_description = st.text_area(
#     "",
#     height=300,
#     placeholder="Paste the job description here..."
# )
# 
# # ============================================================
# # ANALYZE BUTTON
# # ============================================================
# 
# if st.button(
#     "🔍 Analyze Resume",
#     type="primary"
# ):
# 
#     if uploaded_file is None:
# 
#         st.warning(
#             "Please upload your resume."
#         )
# 
#     elif not job_description.strip():
# 
#         st.warning(
#             "Please paste the job description."
#         )
# 
#     else:
# 
#         with st.spinner("Analyzing resume..."):
# 
#             resume_text = extract_resume_text(
#                 uploaded_file
#             )
# 
#             text_similarity_score = (
#                 calculate_text_similarity(
#                     resume_text,
#                     job_description
#                 )
#             )
# 
#             (
#                 skill_match_score,
#                 matched_skills,
#                 missing_skills,
#                 additional_skills
#             ) = calculate_skill_match(
#                 resume_text,
#                 job_description
#             )
# 
#             with st.spinner("🤖 Gemini is analyzing your resume..."):
#               gemini_analysis = analyze_with_gemini(
#                   resume_text,
#                   job_description
#               )
# 
#         # ====================================================
#         # RESULTS
#         # ====================================================
# 
#         st.success("Analysis completed!")
# 
#         st.subheader("📊 Match Scores")
# 
#         col1, col2 = st.columns(2)
# 
#         with col1:
# 
#             st.markdown(
#                 f'<p style="color:white; font-size:20px; font-weight:600;">Text Similarity Score : {text_similarity_score:.2f}%</p>',
#                 unsafe_allow_html=True
#                 )
# 
#         with col2:
# 
#             st.markdown(
#                 f'<p style="color:white; font-size:20px; font-weight:600;">Skill Match Score : {skill_match_score:.2f}%</p>',
#                 unsafe_allow_html=True
#                 )
# 
#         # ====================================================
#         # MATCHED SKILLS
#         # ====================================================
# 
#         st.subheader("✅ Matched Skills")
# 
#         if matched_skills:
# 
#             for skill in matched_skills:
#                 st.write(f"✓ {skill}")
# 
#         else:
# 
#             st.write(
#                 "No matching skills detected."
#             )
# 
# 
#         # ====================================================
#         # MISSING SKILLS
#         # ====================================================
# 
#         st.subheader("❌ Missing Skills")
# 
#         if missing_skills:
# 
#             for skill in missing_skills:
#                 st.write(f"✗ {skill}")
# 
#         else:
# 
#             st.write(
#                 "No missing skills detected."
#             )
# 
# 
#         # ====================================================
#         # ADDITIONAL SKILLS
#         # ====================================================
# 
#         st.subheader("➕ Additional Resume Skills")
# 
#         if additional_skills:
# 
#             for skill in additional_skills:
#                 st.write(f"+ {skill}")
# 
#         else:
# 
#             st.write(
#                 "No additional skills detected."
#             )
# 
#             st.subheader("🤖 Gemini AI Analysis")
#             st.markdown(
#                 gemini_analysis
#             )
#         # ====================================================
#         # EXTRACTED TEXT
#         # ====================================================
# 
#         st.markdown(
#             '<p style="color:white; font-size:20px; font-weight:600;">📄 View Extracted Resume Text</p>',
#               unsafe_allow_html=True
#             )
#         with st.expander("Show Resume Text"):
#           st.markdown(
#               f'<div style="color:white; white-space:pre-wrap;">{resume_text}</div>',
#               unsafe_allow_html=True
#               )

from pyngrok import ngrok
tunnels = ngrok.get_tunnels()

for tunel in tunnels:
  print(tunnel.public_url, "->", tunnel.config["addr"])

public_url = "https://xerox-blazing-multiple.ngrok-free.dev"

print(public_url)

import requests

response = requests.get(public_url)

print(response.status_code)
print(response.headers.get("content-type"))
print(response.text[:300])

!pkill -f "streamlit run app.py"

!streamlit run app.py --server.port 8501 &>/content/streamlit.log &

